- hosts: web
  gather_facts: true
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: no
    - name: password
      prompt: What is your password?

  tasks:

    - name: Your input
      debug: 
        var: username

    - name: The user var was set
      vars:
        user: "{{username}}"
      debug:
        var: user

    - name: Making your file
      shell: touch /tmp/{{user}}.txt

    - name: Adding permissions
      shell: chmod 644 /tmp/{{user}}.txt 
    
    