---
- hosts: node02
  gather_facts: false
  tasks:
  - name: Create files on loop
    debug: var=item
    with_items:
    - foo
    - bar
    - 3

  - name: "loop through list"
    debug:
      msg: "An : {{ item }}"
    with_items:
      - 1
      - 2
      - 3

  - name: add several users
    user:
      name: "{{ item }}"
      groups: "wheel"
      state: present
    with_items:
        - testuser1
        - testuser2

    
  - name: Ensure group "vagrant" exists
    group:
      name: vagrant
      state: present

  - name: more complex items to add several users
    user:
      name: "{{ item.name }}"
      uid: "{{ item.uid }}"
      groups: "{{ item.groups }}"
      state: present
    with_items:
        - { name: testuser1, uid: 1004, groups: "vagrant" }
        - { name: testuser2, uid: 1005, groups: vagrant }

  - name: more complex items to add several users debug
    debug: msg="{{ item.name }}"
    with_items:
        - { name: testuser1, uid: 1006, groups: "vagrant" }
        - { name: testuser2, uid: 1007, groups: vagrant }


