---
- name: install tomcat server
  hosts: web
  become: true

  tasks:
    - name: Install OpenJDK
      yum:
        name: java-1.8.0-openjdk-devel
        state: installed

    - name: make tomcat User
      shell: useradd -m -U -d /opt/tomcat -s /bin/false tomcat

    - name: download tomcat server packages
      yum:
        name: tomcat
        state: installed

    - name: start tomcat services
      shell: systemctl start apache-tomcat-9.0.44/bin/startup.sh