---
- hosts: web  
  tasks:
  - name: Install epel
    shell: yum install epel-release -y
  - name: Install nginx
    shell: yum install nginx -y
  - name: Task 1
    yum: name=nginx state=present
  - name: Task 2 
    service: name=nginx state=started enabled=yes
  - name: Task 3
    file: path=/home/ec2-user/usingAnsible state=directory
  - name: Task 4
    copy: src=../README.md dest=/temp 




ansible -m -m yum -a "name=nginx state=present" node00 --become
ansible -m service -a "name=nginx state=started enabled=yes" node00 --become
ansible -m file -a "path=/home/ec2-user/usingAnsible state=directory" node00 --become
ansible -m copy -a "src=Vagrantfile dest=/tmp" node00 --become