---
- hosts: web  
  vars:
    packages:
     - git
     - httpd
     - nginx

  tasks:
#  - name: Task a 1 
#   shell: mkdir /home/ec2-user/testdirAnsible3
  - name: Task a 2
    copy: src=../inventory/ansible-nodes dest=/tmp/ansible-nodes
  - name: Task a 3
    shell: cat /tmp/ansible-nodes
  - name: Task a 4
    yum: name=httpd state=present
  - name: Task a 5
    yum: name=git state=present
  - name: Task a4, a5, and b1 combined using list var
    yum:
      name: "{{packages}}"
      state: present
    debug: "we ran packages {{packages}}" 
  
#  - name: Task a 6
#   git: repo=https://github.com/becloudready/prometheus_monitoring.git dest=/home/ec2-user/testdirAnsible1 version=HEAD



  - name: Task b 1
    yum: name=nginx state=present
  - name: Task b 2 
    service: name=nginx state=started enabled=yes
  - name: Task b 3
    file: path=/home/ec2-user/usingAnsible state=directory
  - name: Task b 4
    copy: src=../README.md dest=/temp 




